### ISSUE TITLE
Notifications not stable?

### ISSUE THREAD

**Issue by onosAdmin** [nettlep/gobbledegook#1]
Hello Nettlep nice software! I was able to make a gatt server in 10 minutes!
But sometimes the notification part does not work.
I downloaded the last version 6feca1d I can't see any message related to the notiication on the terminal when on the phone (using nRF connect application) I subscribe to the battery notification.
On the phone the value battery characteristic doesn't change until I press read .
The problem happens about one time every 5 ,then I kill the software with ctrl+C and, I run  sudo ./src/standalone -d  again and sometimes it does work.
Tested on debian9 x64 with bluetooth usb Lm506 with bluez5.46   running: bluez-5.46/src/./bluetoothd --experimental -n -d
On bluez I always see (also when there is the problem) :
src/gatt-database.c:ccc_write_cb() External CCC write received with value: 0x0001
and when I disable the notification I see:
src/gatt-database.c:ccc_write_cb() External CCC write received with value: 0x0000

**Comment by nettlep** [comment]
Hi onosAdmin -

Glad to hear it was easy to get up and running for you. You're the first official external feedback I've had.

Unfortunately, I'm unable to reproduce the issue you're seeing, even using nRF as the client. In fact the project I'm working on (the reason I created GGK in the first place) is making heavy use of notifications, but my environment (GGK running on rPI + custom BT client on MacOS/iOS) is very different from yours.

So here are a few notes that might help understand what's going on:

First things first, pull the latest version - I pushed an update shortly before typing this up. I've spent the weekend tracking down some threading issues. I wonder if it is related to one of the issues I resolved.

Stating the obvious just to cover all bases: The battery notification is only sent every 15 seconds which means you might have to wait for almost 15 seconds to receive the first notification after subscribing.

So just to verify: you're seeing `Calling OnUpdatedValue function for interface at path '/com/gobbledegook/battery/level'` in the log but not seeing the notification on the connected/subscribed client? If that's the case, then have you waited through multiple notifications and still receive none of them?

The next thing to check is that there might be an issue with the connection count (a recent addition and so the most suspect.) Once a notification is initiated, it checks the connection count and if there aren't any connections, it doesn't bother sending the notification. You can safely disable this check yourself. Just find the `sendChangeNotificationValue` method at the bottom of `GattCharacteristic.h` and comment out the connection count check.

If that resolves the issue, then let's get a bit more information. Please add the following code as the first line in that method:

`Logger::debug(SSTR << "Connections count for notification is " << HciAdapter::getInstance().getActiveConnectionCount());`

The connection count, of course, should match the number of connections you are actively holding to the server.

I guess at this point, I'll hold off until I hear back.

**Comment by onosAdmin** [comment]
Thank you for the tips, i will try them tomorrow and let you know!

**Comment by onosAdmin** [comment]
Sorry it looks like it was an error on my part, I had modified your code a bit just to add another  notification,

standalone.cpp :

if (!ggkStart("gobbledegook", "Gobbledegook", "Gobbledegook", dataGetter, dataSetter, kMaxAsyncInitTimeoutMS))
	{
		return -1;
	}

	// Wait for the server to start the shutdown process
	//
	// While we wait, every 15 ticks, drop the battery level by one percent until we reach 0
    int  cmd_state=0;   
	while(ggkGetServerRunState() < EStopping)
	{
		std::this_thread::sleep_for(std::chrono::seconds(2));
        if (cmd_state>2){
          cmd_state=0;
        }
        else{
          cmd_state=cmd_state+1;
        }
		serverDataBatteryLevel = std::max(serverDataBatteryLevel - 1, 0);
		ggkNofifyUpdatedCharacteristic("/com/gobbledegook/battery/level");

	    clock_gettime(CLOCK_REALTIME, &time0);
	    timeStamp = time0.tv_sec;
	    nanoSeconds = time0.tv_nsec;

        switch(cmd_state) {
          case 0:
            Cmd1[0]=3;
            Cmd1[1]=1;
            Cmd1[2]=1;
            Cmd1[3]=1;

            ggkNofifyUpdatedCharacteristic("/com/gobbledegook/mycmd/cmd1"); 
            break;

          case 1:
            Cmd1[0]=3;
            Cmd1[1]=1;
            Cmd1[2]=1;
            Cmd1[3]=0;
            ggkNofifyUpdatedCharacteristic("/com/gobbledegook/mycmd/cmd1");
            break;

        }

	}

I modified the switch case with :  


        switch(cmd_state) {
          case 0:
            Cmd1[0]=3;
            Cmd1[1]=1;
            Cmd1[2]=1;
            Cmd1[3]=1;


            break;

          case 1:
            Cmd1[0]=3;
            Cmd1[1]=1;
            Cmd1[2]=1;
            Cmd1[3]=0;

            break;

        }
          ggkNofifyUpdatedCharacteristic("/com/gobbledegook/mycmd/cmd1"); 

	}

Now it is working with the last commit everytimes! sorry for the false bug report.

**Comment by nettlep** [comment]
Ah, that's okay. It happens.

Quick note: I don't know your intentions, but as written, every third iteration through the loop, your code will set `cmd_state` equal to `2` and send a notification with no updated value. If this isn't your intention, you might want to change `if (cmd_state>2)` to `if (cmd_state>=2)`.

I know it's none of my business, just thought I'd point it out.

**Comment by onosAdmin** [comment]
Thank you!, anyway i have another question, I'm not good at c++ but i'm trying to send this commands in sequence:3111 and then 3110   i need them to be byte...the 3111 sequence is displayed correctly on the phone client...but the 3110 is stopped after the last 1 so i see 311  not 3110 , i think is a problem derived from the string closing with the 0 is there any way to bypass the problem?

**Comment by nettlep** [comment]
I don't have access to the relevant parts of your code, so I'll take a stab in the dark:

In your new service (`mycmd/cmd1` in `Server.cpp`) your call to `methodReturnValue` probably looks something like this:

```
// Cmd1 is probably declared as a char *
self.methodReturnValue(pInvocation, Cmd1, true);
```

Return values of type `char *` are treated as strings. You can easily convert it to an array of bytes, which will just send your raw data. Try changing it to:

```
// Convert to a common byte type
const uint8_t *pBuffer = reinterpret_cast<uint8_t *>(Cmd1);

// The number of bytes you want to send (I set to 4 since that seems to be what you're doing)
int count = 4;

// Create a byte array
std::vector<uint8_t> buffer(pBuffer, pBuffer + count);

// Send the array of raw bytes
self.methodReturnValue(pInvocation, buffer, true);
```

The same holds true for calls to `sendChangeNotificationValue` (you'll want the second parameter to this method to be an array of bytes.)

**Comment by onosAdmin** [comment]
Thank you very much !!! I will try
