### ISSUE TITLE
ATT error: 0x0e (unlikely) after write

### ISSUE THREAD

**Issue by br101** [nettlep/gobbledegook#12]
When I try to write the "text/string" characteristic in the unmodified standalone.cpp / Server.cpp I get the error 0x0e (unlikely). When using gatt-python this error shows as  `'Operation failed with ATT error: 0x0e'` and with nRF Connect I get `Write operation failed: BLE_GATT_STATUS_ATTERR_UNLIKELY_ERROR (0x010E)`.

I have tested with bluez 5.48 and 5.45 on Ubuntu 18.04 and I don't see useful debug information in the logs, the error is not mentioned neither by bluetoothd nor gobbledegook. btmon shows me the error is sent:

```
Bluetooth monitor ver 5.48
= Note: Linux version 4.15.0-42-generic (x86_64)                                             0.728855
= Note: Bluetooth subsystem version 2.22                                                     0.728857
= New Index: BA:27:EB:BB:B3:40 (Primary,USB,hci0)                                     [hci0] 0.728857
= Open Index: BA:27:EB:BB:B3:40                                                       [hci0] 0.728858
= Index Info: BA:27:EB:BB:B3:40 (Cambridge Silicon Radio)                             [hci0] 0.728858
@ MGMT Open: standalone (privileged) version 1.14                                   {0x0003} 0.728859
@ MGMT Open: bluetoothd (privileged) version 1.14                                   {0x0002} 0.728859
@ MGMT Open: bluetoothd (privileged) version 1.14                                   {0x0001} 0.728859
@ MGMT Open: btmon (privileged) version 1.14                                        {0x0004} 0.728939
> ACL Data RX: Handle 68 flags 0x02 dlen 12                                        #1 [hci0] 9.186933
      ATT: Write Request (0x12) len 7
        Handle: 0x0037
          Data: 6262626262
< ACL Data TX: Handle 68 flags 0x00 dlen 9                                        #2 [hci0] 14.192821
      ATT: Error Response (0x01) len 4
        Write Request (0x12)
        Handle: 0x0037
        Error: Unlikely Error (0x0e)
> HCI Event: Number of Completed Packets (0x13) plen 5                            #3 [hci0] 14.272507
        Num handles: 1
        Handle: 68
        Count: 1
```

I suppose it may be related to the write response mentioned in #6, as, when I run the `example-gatt-server` from bluez my test application receives a write response and all is OK.

Also when I change the characteristic to "write-without-response" it works OK - but without write responses...
`.gattCharacteristicBegin("string", "00000002-1E3C-FAD4-74E2-97A033F1BFAA", {"read", "write-without-response", "notify"})`

**Comment by mikaku** [comment]
Hi @br101, it looks like this can be linked to my (closed) issue #9.

I'm still have the same problem, not fixed yet. So as soon as you find the solution, please, share it.
Thanks.

**Comment by br101** [comment]
Yes I've seen your #9 ... my fix for now is to use "write-without response" as mentioned, but that can not be the real solution...

**Comment by mikaku** [comment]
@br101, good job!
Thank you very much.

**Comment by brett-lynnes** [comment]
Thanks for the patch. This was a problem we were having too and I was really scratching my head trying to figure out what I was doing wrong with gdbus.
