### ISSUE TITLE
Gobbledegook and TI Sensor Tag

### ISSUE THREAD

**Issue by westsuhanic** [nettlep/gobbledegook#19]
Hello:

Could I use your library to communicate with a TI Sensor Tag?

I currently use the tinyb library to talk to the TI Sensor Tag. However issues have popped up
and I am not getting any support. So I am looking or alternatives.

Tinyb  uses dbus to talk to bluetoothd.

thank you,
west suhanic

**Comment by nettlep** [comment]
I'm not familiar with the TI Sensor Tag. However, a quick look around the tinyb sample for talking to that device, it looks like you need a BLE client, not a server. As GGK is a server, it's probably not what you want.
