### ISSUE TITLE
Library compatible to BlueZ 5.37?

### ISSUE THREAD

**Issue by S3ler** [nettlep/gobbledegook#2]
Hi,
first of all: Looks like a great library.

I programmed a BLE Library myself for a project but only the central device part is working.
Now I wanted to build a NUS ([Nordic UART Service](https://devzone.nordicsemi.com/documentation/nrf51/6.0.0/s110/html/a00066.html)) example (basically BLE-Chat) with a peripheral device using your library and mine for the central device.
It would be really nice to see such an example.
My was implemented against BlueZ 5.37 (with experimental flag, but 5.37 was the preinstalled version) and now it is not clear if the goobledegook library will work with 5.37.

So my fist **question** is now: Does your library only work with BlueZ 5.45 or is the D-Bus API version 5.45 different to the version 5.37?

**Comment by nettlep** [comment]
I've not tested on BlueZ 5.37, but I would be wary of the GATT D-Bus support in that version. It's a very early iteration of their GATT D-Bus support and there have been many changes/fixes since.
