### ISSUE TITLE
ERROR: Unsupported response event type: 0x0011 (Authentication failed event)

### ISSUE THREAD

**Issue by thamel29446** [nettlep/gobbledegook#22]
Hi!

This is a real problem. Tried several distros all with BLUEZ 5.50 always the same when connecting with iPhone. Was working great with Bluez 5.43

Now I get:
ERROR: Unsupported response event type: 0x0011 (Authentication failed event)

Same as reported by others here.

Any hints?

Thanks!
Tim

**Comment by mikaku** [comment]
There is already the issue #20 with almost the same title.
Nothing new, though.

**Comment by mikekolesov** [comment]
Resolved this issue by turning off some builtin plugins of Bluez 5.50, which are used to get some extra info of connected devices.
Set bluetoothd option --noplugin=hostname,scanparam,battery

In my case, iOS posts some extra internal BLE services (not app related services, like battery info and so on). Bluez 5.50 finds these services and asks for accessing that data with default authentication setting. In case of GobbleDeGook client, default is no auth. iOS rejects such no auth access of Bluez. Bluez forwards auth error to GobbleDeGook client. **After near 30s of such retries iOS disconnects**. I guest iOS treats such long retries like DDOS from peripheral or so and decides to stop connection.

**Comment by nettlep** [comment]
Thanks for the info!

**Comment by mikaku** [comment]
@mikekolesov 

> Resolved this issue by turning off some builtin plugins of Bluez 5.50, which are used to get some extra info of connected devices.
Set bluetoothd option --noplugin=hostname,scanparam,battery

This also worked with Bluez 5.52 :smiley:

Thank you very much!
