### ISSUE TITLE
Advertising Interval

### ISSUE THREAD

**Issue by tknight00** [nettlep/gobbledegook#23]
[nRF Connect](https://www.nordicsemi.com/?sc_itemid=%7B41FF7A0B-B565-420A-95B7-B32122B5D3AD%7D) is showing my ggk server as having a 1281ms adv. interval. Is there some way of increasing the speed of the advertising interval? Most other devices are around 40ms.

Looks like there is a [hcitool command](https://stackoverflow.com/questions/21124993/is-there-a-way-to-increase-ble-advertisement-frequency-in-bluez) that may be applicable.

**Comment by stez-mind** [comment]
You can also write to these values in sysfs:

`/sys/kernel/debug/bluetooth/hci0/adv_min_interval
/sys/kernel/debug/bluetooth/hci0/adv_max_interval
`
The values should be in milliseconds. Works fine for me (BlueZ 5.48).
