### ISSUE TITLE
Discovering GATT Services: Error 22 (0x16) terminate local host

### ISSUE THREAD

**Issue by tknight00** [nettlep/gobbledegook#24]
I'm currently running the standalone binary without modification (BlueZ 5.48).

nRF Connect is able to discover the device via its scanner.  However, the nRF Connect fails during "Discovering services..." which leads to a disconnect. The error message is "Error 22 (0x16): GATT CONN TERMINATE LOCAL HOST".

The standalone server produces no log event during the nRF service discovery failure

**Comment by tknight0000** [comment]
The issue was that I was running it in a VM. I switched to a "real" env and the problem went away.

**Comment by tknight00** [comment]
The issue was that I was running it in a VM. I switched to a "real" env and the problem went away.

**Comment by nettlep** [comment]
Thanks for reporting back with your results!
