### ISSUE TITLE
Can i cross-compile gobbledegook for ARM

### ISSUE THREAD

**Issue by vanduong** [nettlep/gobbledegook#4]
i want to cross-compile gobbledegook for ARM because i use AM3358 Processer, and it too slow to compile gobbledegook.
So can you tell me, how can i cross-compile gobbledegook for ARM, thank you very much.

**Comment by nettlep** [comment]
I am cross-compiling for the rPI on macOS, but setting this up is not a trivial matter.

It involves building or finding a pre-built toolchain - a C++ compiler that runs on the local machine with a linker like Gold linker capable of generating ARM code in the correct binary format. You'll also need an SDK - the native libraries and headers from the target platform.

Start by finding the proper toolchain. You could do the legwork yourself and build your own, but if you're not familiar with this process it can be a rocky road while you're learning it. Once you have a toolchain, the SDK can be had by simply copying the necessary files from the target to your host. If you can't find an SDK, a local copy of the target's filesystem would suffice.

**Comment by vanduong** [comment]
Many thanks for your reply,
I'm using Linaro toolchain, with other software like Asterisk, ... i can cross-compile by command:
./configure --host=arm-linux-gnueabihf
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- + a parameter link to kernel headers
......
Can you tell me more detail about the way you compile for the rPI on macOS? Thanks.

**Comment by mmueller-kaffeeschluerfercom** [comment]
Thread seems closed but not solved. I stumbled upon the same problem and tried several hours. But finally, it worked. I have cross-compiled with the Linaro toolchain for Raspberry Pi (Raspbian) on Linux with following command:

`make CXX="rPI_Toolchain/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -std=gnu++11 --sysroot=$RASPSYSROOT" LIBS="-lgobject-2.0 -lgio-2.0 -lglib-2.0 -lpthread -lpcre"`

Of course you'll have to adapt the toolchain directory and the sysroot. For sysroot, I just copied the whole /usr and /lib of raspberry pi in a local folder.

Then, to include the library into your own program, you also have to link to the same libraries: `-lgobject-2.0 -lgio-2.0 -lglib-2.0 -lpthread -lpcre`

**Comment by nettlep** [comment]
Here's how I was building it. This doesn't require a complete toolchain to be installed as it uses the Mac's `clang`.

You're going to need an SDK.

**Important:** Before creating your SDK, you'll need to ensure you have the GGK prerequisites installed on your rPI. These include the development tools, `Bluez`, `glib`, `dbus` (and possibly more that I've forgotten.) Basically, everything you would need to build it on the rPI. A good idea is to get it building on the rPI first to ensure everything is configured correctly.

Now you can create your SDK in the same way that @mmueller-kaffeeschluerfercom  suggested, by copying all of `/usr` and `/lib` from the rPI to a local folder on the Mac.

You'll also need the gold linker (binary named `ld.gold`) installed on your Mac. Mine was built from source.

Copy the following script into a file called `build.sh` in the GGK root directory (i.e., the parent of the `src` directory):

```
export TOOLCHAIN_SDK="<your sdk directory here>"

clang++ -g -O0 -DDEBUG \
		-target armv7-unknown-linux-gnueabihf \
		-fPIC \
		-std=c++11 \
		-Wall \
		-Wextra \
		-nostdinc \
		-isysroot "$TOOLCHAIN_SDK" \
		-I"$TOOLCHAIN_SDK/usr/include" \
		-I"$TOOLCHAIN_SDK/usr/include/arm-linux-gnueabihf" \
		-I"$TOOLCHAIN_SDK/usr/include/arm-linux-gnueabihf/c++/5" \
		-I"$TOOLCHAIN_SDK/usr/include/c++/5" \
		-I"$TOOLCHAIN_SDK/usr/include/dbus-1.0" \
		-I"$TOOLCHAIN_SDK/usr/include/glib-2.0" \
		-I"$TOOLCHAIN_SDK/usr/lib/gcc/arm-linux-gnueabihf/5/include" \
		-I"$TOOLCHAIN_SDK/usr/lib/arm-linux-gnueabihf/glib-2.0/include" \
		-I"$TOOLCHAIN_SDK/usr/lib/arm-linux-gnueabihf/dbus-1.0/include" \
		-I"$TOOLCHAIN_SDK/usr/lib/clang/5.0.0/include" \
		-I"include" \
		-c src/*.cpp
ld.gold \
		-shared \
		-lc \
		-lgcc_s \
		-lstdc++ \
		-lpthread \
		--sysroot "$TOOLCHAIN_SDK" \
		-L"$TOOLCHAIN_SDK/usr/lib/arm-linux-gnueabihf" \
		-L"$TOOLCHAIN_SDK/usr/lib/gcc/arm-linux-gnueabihf/5" \
		"$TOOLCHAIN_SDK/usr/lib/gcc/arm-linux-gnueabihf/5/crtbeginS.o" \
		"$TOOLCHAIN_SDK/usr/lib/gcc/arm-linux-gnueabihf/5.4.0/crtendS.o" \
		*.o \
		-o "libgobbledegook.so"
```

Edit the `TOOLCHAIN_SDK` variable in the script to point to your SDK directory. Also, don't forget to mark the script as executable (with `chmod +x build.sh`).

Run `./build.sh`. If it worked, you'll have a `libgobbledegook.so` file in the current directory. This is the rPI version.

Troubleshooting:

This script is based off of a `Ubuntu Xenial` distro for rPI. If you're using a different distro, it should be easy to get it working by adjusting the include/library paths to match your distribution.

**Comment by BogdanovL** [comment]
Figured I'd add my two cents here for the future karma. 
I wanted to build the standalone app. Here's what I finally settled on:
```
export TOOLCHAIN_SDK="<MY_RPI_SDK>" \

<RPI_TOOLS>/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++ \
-fPIC \
-Wall \
-Wextra \
-std=c++11 \
--sysroot $TOOLCHAIN_SDK \
-I"$TOOLCHAIN_SDK/usr/lib/arm-linux-gnueabihf/glib-2.0/include" \
-I"$TOOLCHAIN_SDK/usr/include/libmount" \
-I"$TOOLCHAIN_SDK/usr/include/blkid" \
-I"$TOOLCHAIN_SDK/usr/include/glib-2.0" \
-I"$TOOLCHAIN_SDK/usr/include" \
-I"$TOOLCHAIN_SDK/usr/include/arm-linux-gnueabihf" \
-pthread \
-g \
-O2 \
-o standalone \
src/*.cpp \
-L "$TOOLCHAIN_SDK/lib/arm-linux-gnueabihf" \
-L "$TOOLCHAIN_SDK/usr/lib/arm-linux-gnueabihf" \
-lgobject-2.0 -lgio-2.0 -lglib-2.0 -lpthread
```
