### ISSUE TITLE
g_auto() undefined

### ISSUE THREAD

**Issue by ihassin** [nettlep/gobbledegook#5]
Hi,

I've just forked and am trying to build the lib and app.
I am on a Pi, using:
pi@pi ~/projects/gobbledegook $ g++ --version
g++ (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I am getting a syntax error concerning g_auto():

Utils.cpp: In static member function ‘static GVariant* ggk::Utils::gvariantFromStringArray(const char*, va_list)’:
Utils.cpp:245:24: error: expected primary-expression before ‘)’ token
  g_auto(GVariantBuilder) builder;
**Utils.cpp:245:24: error: ‘g_auto’ was not declared in this scope**

Since I am completely new to all this, and by sheer brut force, it passes if I remove all references to g_auto and simply use:

GVariantBuilder builder;

I wanted your guidance please, in this regards. I am sure it's a problem on my side, and would like your help in resolving it, if possible.

If it's an oversight (which I doubt) and we need to get rid of g_auto(), then I'll open a PR.

Thanks!
Itamar

**Comment by rmartens** [comment]
[g_auto](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#g-auto) is part of glib, you will need to update glib to a version newer than 2.44 for it to incude g_auto.

**Comment by ihassin** [comment]
Ooops! Sorry! Thanks for answering.

**Comment by sauadwaya** [comment]
Hi...can you tell me how exactly to update the most recent version of glib? (or atleat greater than 2.44)
