### ISSUE TITLE
to send large amount of data

### ISSUE THREAD

**Issue by fvisztra** [nettlep/gobbledegook#8]
hi,

I'd like to send large amount of data, but I don't know how to maximise the speed to send to iOS...but I don't know what the problem with my code :(
could you take a look at?

.gattCharacteristicBegin("toPhone", "********-****-****-****-************", {"read", "notify"})
          .onReadValue(CHARACTERISTIC_METHOD_CALLBACK_LAMBDA
          {
              int16_t cpuCount = 4;
              self.methodReturnValue(pInvocation, cpuCount, true);
          })

          .onUpdatedValue(CHARACTERISTIC_UPDATED_VALUE_CALLBACK_LAMBDA
          {
            const std::vector<guint8> Default;
            const std::vector<guint8>* pDataVec = self.getDataPointer<const std::vector<guint8>*>("Data/toPhone",&Default);

              size_t pos = 0;
              size_t left = pDataVec->size();
              const size_t MaxNumtoSend = 100;
              while( left > 0 )
              {
                  const size_t toSend = left > MaxNumtoSend ? MaxNumtoSend : left ;
                  const std::vector<uint8_t> chunk(pDataVec->data() + pos , pDataVec->data() + pos + toSend);
                  self.sendChangeNotificationValue(pConnection,chunk);
                  pos += toSend;
                  left -= toSend;
              }
            self.clearDataPointer("Data/toPhone");
            return true;
          })
      .gattCharacteristicEnd()

thank you very much

**Comment by nettlep** [comment]
Unfortunately, GGK isn't intended for large amounts of data as it doesn't support multimedia streaming.

You might have a look at: https://punchthrough.com/pt-blog-post/maximizing-ble-throughput-on-ios-and-android/
